### ISSUE TITLE
It looks like you are using some plugin(s) that alter how Skript works

### ISSUE THREAD

**Issue by Vxnku** [SkriptHub/SkriptHub#88]
I have this
[10:31:55 ERROR]: #!#! 
[10:31:55 ERROR]: #!#! [Skript] Severe Error:
[10:31:55 ERROR]: #!#! Could not load fall.sk
[10:31:55 ERROR]: #!#! 
[10:31:55 ERROR]: #!#! Something went horribly wrong with Skript.
[10:31:55 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[10:31:55 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[10:31:55 ERROR]: #!#! Here is full list of them:
[10:31:55 ERROR]: #!#! skRayFall v1.9.27 (https://sk.rayfall.net/) SkQuery v4.1.6 Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/) 
[10:31:55 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[10:31:55 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[10:31:55 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[10:31:55 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[10:31:55 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[10:31:55 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[10:31:55 ERROR]: #!#! 
[10:31:55 ERROR]: #!#! Stack trace:
[10:31:55 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[10:31:55 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Condition.parse(Condition.java:77)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.init(Section.java:69)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:257)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.parse(Section.java:156)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1127)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:752)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1060)
[10:31:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[10:31:55 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:31:55 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[10:31:55 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:908)
[10:31:55 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2289)
[10:31:55 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2100)
[10:31:55 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2081)
[10:31:55 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[10:31:55 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[10:31:55 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[10:31:55 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[10:31:55 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[10:31:55 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[10:31:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1423)
[10:31:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[10:31:55 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[10:31:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400)
[10:31:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1393)
[10:31:55 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[10:31:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1371)
[10:31:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1277)
[10:31:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[10:31:55 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[10:31:55 ERROR]: #!#! 
[10:31:55 ERROR]: #!#! Version Information:
[10:31:55 ERROR]: #!#!   Skript: 2.6.1 (latest)
[10:31:55 ERROR]: #!#!     Flavor: skriptlang-github
[10:31:55 ERROR]: #!#!     Date: 22:18:42.554713200
[10:31:55 ERROR]: #!#!   Bukkit: 1.18.1-R0.1-SNAPSHOT
[10:31:55 ERROR]: #!#!   Minecraft: 1.18.1
[10:31:55 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[10:31:55 ERROR]: #!#!   OS: Linux amd64 5.4.0-107-generic
[10:31:55 ERROR]: #!#! 
[10:31:55 ERROR]: #!#! Server platform: Paper
[10:31:55 ERROR]: #!#! 
[10:31:55 ERROR]: #!#! Current node: on cause damage is fall: (fall.sk, line 2)
[10:31:55 ERROR]: #!#! Current item: null
[10:31:55 ERROR]: #!#! 
[10:31:55 ERROR]: #!#! Thread: Server thread
[10:31:55 ERROR]: #!#! 
[10:31:55 ERROR]: #!#! Language: english
[10:31:55 ERROR]: #!#! Link parse mode: DISABLED
[10:31:55 ERROR]: #!#! 
[10:31:55 ERROR]: #!#! End of Error.
[10:31:55 ERROR]: #!#! 

Skript

fall.sk
on damage:
	on cause damage is fall:
		send "%player% test" to player

**Comment by HYPExMon5ter** [comment]
Wrong github, please close this issue and report this bug [here](https://github.com/SkriptLang/Skript/issues).
